# Generated by Django 4.2.10 on 2024-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200)),
                ('className', models.CharField(max_length=200)),
                ('professorName', models.CharField(max_length=200)),
                ('studentName', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('workType', models.CharField(max_length=200)),
                ('fileLink', models.CharField(max_length=500)),
            ],
        ),
    ]
