# Generated by Django 5.0.2 on 2024-03-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200)),
                ('className', models.CharField(max_length=200)),
                ('professorName', models.CharField(max_length=200)),
                ('studentName', models.CharField(max_length=200)),
                ('ratings', models.CharField(max_length=200)),
                ('workType', models.CharField(max_length=200)),
                ('fileLink', models.CharField(max_length=500)),
            ],
        ),
    ]
