# Generated by Django 5.0.2 on 2024-03-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='ratings',
            new_name='rating',
        ),
    ]
