# Generated by Django 4.2.10 on 2024-04-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email_prof',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
