# Generated by Django 4.2.10 on 2024-04-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_report_email_prof_report_private_report_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='professor_email',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
