# Generated by Django 4.2.10 on 2024-03-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_document_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200)),
                ('className', models.CharField(max_length=200)),
                ('professorName', models.CharField(max_length=200)),
                ('studentName', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('workType', models.CharField(max_length=200)),
                ('fileLink', models.CharField(max_length=500)),
            ],
        ),
    ]
