# Generated by Django 4.2.10 on 2024-04-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_report_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
    ]
