# Generated by Django 4.2.10 on 2024-04-26 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_report_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
