# Generated by Django 4.2.10 on 2024-04-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_report_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
