# Generated by Django 4.2.10 on 2024-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_type',
            field=models.CharField(default='pdf', max_length=10),
        ),
    ]
